np.array()에는 다양한 원소들로 구성된 리스트를 통해 배열 생성 가능하나 내부 데이터 type은 하나로 통일되어야 한다.  
따라서 문자열로 통일된다.  

In [33]:
import numpy as np
a = [1, 2, 'ab', 'zz']
np.array(a)

array(['1', '2', 'ab', 'zz'], dtype='<U11')

In [34]:
a = [1, 'a', True]
np.array(a)

array(['1', 'a', 'True'], dtype='<U11')

Reshape

In [1]:
import numpy as np

In [3]:
a = np.arange(6)
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [4]:
# order, C: c-like, F: fotran like
np.reshape(a, newshape=(1, 6), order = 'C')

array([[0, 1, 2, 3, 4, 5]])

Array Convert  
- np.newaxis, np.expand_dims  

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape, a

((6,), array([1, 2, 3, 4, 5, 6]))

In [6]:
a2 = a[np.newaxis,:]
a2.shape, a2

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

1x6의 구조를 가져야 row vector

In [11]:
row_vector = a[np.newaxis, :]
row_vector.shape, row_vector

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

In [10]:
col_vector = a[:, np.newaxis]
col_vector.shape, col_vector

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [12]:
b = np.expand_dims(a, axis=1)
b.shape, b

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

In [14]:
c = np.expand_dims(a, axis=0)
c.shape, c

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

Indexing & Slicing

In [16]:
data = np.array([1, 2, 3])
data[-2], data[-2:]

(2, array([2, 3]))

In [23]:
# just value selection
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
six_up = a > 6
divisible_by_2 = (a%2==0)
cond = (a>2)&(a<11)
a[a<6], a[six_up], a[divisible_by_2], a[cond]

(array([1, 2, 3, 4, 5]),
 array([ 7,  8,  9, 10, 11, 12]),
 array([ 2,  4,  6,  8, 10, 12]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10]))

In [24]:
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

np.nonzero()는 () 조건에 부합하는 True 요소의 index를 반환한다.

In [26]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [28]:
# 다음과 같은 index 위치를 생성할 수 있다.
list(zip(b[0], b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [31]:
# 해당 조건에 부합하는 원소를 다음과 같이 호출할 수 있으나, 
# a[a<5]로 바로 호출될 수 있으므로, 크게 의미없을 듯.
a[b], a[a<5]

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

np.vstack(), np.hstack(), np.hsplit(), view(), copy()

In [37]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [39]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [41]:
np.vstack((a1, a2)), np.hstack((a1, a2))

(array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]]),
 array([[1, 1, 3, 3],
        [2, 2, 4, 4]]))

In [42]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

split을 하면 array로 이뤄진 리스트가 반환된다. 

In [44]:
np.hsplit(x, 3), type(np.hsplit(x, 3))

([array([[ 1,  2,  3,  4],
         [13, 14, 15, 16]]),
  array([[ 5,  6,  7,  8],
         [17, 18, 19, 20]]),
  array([[ 9, 10, 11, 12],
         [21, 22, 23, 24]])],
 list)